main: main.cpp Bitmap.cpp Bitmap.h
	g++ -o main main.cpp Bitmap.cpp
debug: main.cpp Bitmap.cpp Bitmap.h
	g++ -g -o main main.cpp Bitmap.cpp
tar: main.cpp Bitmap.h Bitmap.cpp makefile
	tar -zcvf Not_Found.tar $^